### ISSUE TITLE
附加卡片文字渲染异常

### ISSUE THREAD

**Issue by blyc** [BalconyJH/DynRender#1]
大佬，请问调用库之后生成的图片其他地方字体正常，但附加卡片的 ‘预约’ 两字是方块，是我哪里做得不对吗？能请教下该怎么解决吗？
用的版本是git拉取的当前最新代码

![图片](https://github.com/BalconyJH/DynRender/assets/34291620/11e175d8-735a-41fd-9377-9ddb5278577d)

动态id：822504963263430656

**Comment by BalconyJH** [comment]
装点别的字体 
https://github.com/laishulu/Sarasa-Term-SC-Nerd

**Comment by blyc** [comment]
> 装点别的字体 https://github.com/laishulu/Sarasa-Term-SC-Nerd

可以了，谢谢大佬
（以及库也相当好用，感谢
