### ISSUE TITLE
暂不支持的特殊MAJOR_TYPE   “DYNAMIC_TYPE_NONE”

### ISSUE THREAD

**Issue by blyc** [BalconyJH/DynRender#2]
如文末动态链接，
转发动态 的 源动态若已删除，则 MAJOR_TYPE 返回为 “DYNAMIC_TYPE_NONE”
请问大佬是否有支持的计划？

示例动态链接：https://t.bilibili.com/503869671795764230

**Comment by BalconyJH** [comment]
先放着，不一定有空写

**Comment by blyc** [comment]
谢谢大佬，测试了0.2.0版本已经支持了
